export const TOOLS = [
  // ── Organize PDF ─────────────────────────────────────────────────────────
  {
    id: 'merge',
    route: '/merge',
    name: 'Merge PDF',
    desc: 'Combine multiple PDFs into one document',
    icon: 'merge',
    color: '#DC2626',
    bg: '#FEF2F2',
    category: 'organize',
    multi: true,
    endpoint: '/api/merge',
    accept: '.pdf',
    actionLabel: 'Merge PDFs',
  },
  {
    id: 'split',
    route: '/split',
    name: 'Split PDF',
    desc: 'Extract specific pages from a PDF file',
    icon: 'split',
    color: '#EA580C',
    bg: '#FFF7ED',
    category: 'organize',
    endpoint: '/api/split',
    accept: '.pdf',
    actionLabel: 'Split PDF',
    options: [
      {
        name: 'pages',
        label: 'Pages to extract',
        type: 'text',
        placeholder: '1-3, 5, 7-10  (leave blank for all)',
        default: '',
        hint: 'Use ranges like 1-5 or individual pages like 2,4,6',
      },
    ],
  },
  {
    id: 'compress',
    route: '/compress',
    name: 'Compress PDF',
    desc: 'Reduce PDF file size without losing quality',
    icon: 'compress',
    color: '#16A34A',
    bg: '#F0FDF4',
    category: 'organize',
    endpoint: '/api/compress',
    accept: '.pdf',
    actionLabel: 'Compress PDF',
  },
  {
    id: 'rotate',
    route: '/rotate',
    name: 'Rotate PDF',
    desc: 'Rotate all pages in your PDF document',
    icon: 'rotate',
    color: '#2563EB',
    bg: '#EFF6FF',
    category: 'organize',
    endpoint: '/api/rotate',
    accept: '.pdf',
    actionLabel: 'Rotate Pages',
    options: [
      {
        name: 'degrees',
        label: 'Rotation direction',
        type: 'select',
        default: '90',
        choices: [
          { value: '90',  label: '90° Clockwise' },
          { value: '180', label: '180° (Flip)' },
          { value: '270', label: '90° Counter-clockwise' },
        ],
      },
    ],
  },

  // ── Edit PDF ──────────────────────────────────────────────────────────────
  {
    id: 'edit-pdf',
    route: '/edit-pdf',
    name: 'Edit PDF',
    desc: 'Add text, match fonts, and white-out content on any page',
    icon: 'edit',
    color: '#0891B2',
    bg: '#ECFEFF',
    category: 'edit',
    editor: true,
    accept: '.pdf',
    actionLabel: 'Edit PDF',
  },
  {
    id: 'watermark',
    route: '/watermark',
    name: 'Watermark PDF',
    desc: 'Stamp a text watermark across every page',
    icon: 'watermark',
    color: '#7C3AED',
    bg: '#F5F3FF',
    category: 'edit',
    endpoint: '/api/watermark',
    accept: '.pdf',
    actionLabel: 'Add Watermark',
    options: [
      {
        name: 'text',
        label: 'Watermark text',
        type: 'text',
        placeholder: 'CONFIDENTIAL',
        default: 'CONFIDENTIAL',
      },
      {
        name: 'opacity',
        label: 'Opacity',
        type: 'range',
        min: '0.05', max: '0.5', step: '0.05',
        default: '0.25',
        format: v => `${Math.round(v * 100)}%`,
      },
    ],
  },
  {
    id: 'page-numbers',
    route: '/page-numbers',
    name: 'Page Numbers',
    desc: 'Add page numbers to your PDF document',
    icon: 'pagenum',
    color: '#DB2777',
    bg: '#FDF2F8',
    category: 'edit',
    endpoint: '/api/page-numbers',
    accept: '.pdf',
    actionLabel: 'Add Page Numbers',
    options: [
      {
        name: 'position',
        label: 'Position',
        type: 'select',
        default: 'bottom-center',
        choices: [
          { value: 'bottom-center', label: 'Bottom Center' },
          { value: 'bottom-right',  label: 'Bottom Right' },
          { value: 'bottom-left',   label: 'Bottom Left' },
          { value: 'top-center',    label: 'Top Center' },
          { value: 'top-right',     label: 'Top Right' },
          { value: 'top-left',      label: 'Top Left' },
        ],
      },
      {
        name: 'startAt',
        label: 'Start numbering at',
        type: 'number',
        default: '1',
        min: '1',
        max: '999',
      },
    ],
  },

  // ── Convert to PDF ────────────────────────────────────────────────────────
  {
    id: 'word-to-pdf',
    route: '/word-to-pdf',
    name: 'Word to PDF',
    desc: 'Convert Word documents to PDF format',
    icon: 'word',
    color: '#1D4ED8',
    bg: '#EFF6FF',
    category: 'to-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'pdf' },
    accept: '.docx,.doc,.odt,.rtf',
    actionLabel: 'Convert to PDF',
  },
  {
    id: 'excel-to-pdf',
    route: '/excel-to-pdf',
    name: 'Excel to PDF',
    desc: 'Convert spreadsheets to PDF format',
    icon: 'excel',
    color: '#15803D',
    bg: '#F0FDF4',
    category: 'to-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'pdf' },
    accept: '.xlsx,.xls,.ods,.csv',
    actionLabel: 'Convert to PDF',
  },
  {
    id: 'ppt-to-pdf',
    route: '/ppt-to-pdf',
    name: 'PowerPoint to PDF',
    desc: 'Convert presentations to PDF format',
    icon: 'ppt',
    color: '#C2410C',
    bg: '#FFF7ED',
    category: 'to-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'pdf' },
    accept: '.pptx,.ppt,.odp',
    actionLabel: 'Convert to PDF',
  },
  {
    id: 'image-to-pdf',
    route: '/image-to-pdf',
    name: 'Image to PDF',
    desc: 'Convert JPG, PNG and other images to PDF',
    icon: 'image',
    color: '#0369A1',
    bg: '#F0F9FF',
    category: 'to-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'pdf' },
    accept: '.jpg,.jpeg,.png,.gif,.webp,.bmp,.svg',
    actionLabel: 'Convert to PDF',
  },
  {
    id: 'html-to-pdf',
    route: '/html-to-pdf',
    name: 'HTML to PDF',
    desc: 'Convert HTML files to PDF documents',
    icon: 'html',
    color: '#7C3AED',
    bg: '#F5F3FF',
    category: 'to-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'pdf' },
    accept: '.html,.htm',
    actionLabel: 'Convert to PDF',
  },

  // ── Convert from PDF ──────────────────────────────────────────────────────
  {
    id: 'pdf-to-word',
    route: '/pdf-to-word',
    name: 'PDF to Word',
    desc: 'Convert PDF to an editable Word document',
    icon: 'pdf-word',
    color: '#4338CA',
    bg: '#EEF2FF',
    category: 'from-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'docx' },
    accept: '.pdf',
    actionLabel: 'Convert to Word',
  },
  {
    id: 'pdf-to-images',
    route: '/pdf-to-images',
    name: 'PDF to Images',
    desc: 'Convert PDF pages to PNG images',
    icon: 'pdf-img',
    color: '#BE185D',
    bg: '#FDF2F8',
    category: 'from-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'png' },
    accept: '.pdf',
    actionLabel: 'Convert to Images',
  },
  {
    id: 'pdf-to-text',
    route: '/pdf-to-text',
    name: 'PDF to Text',
    desc: 'Extract plain text content from a PDF',
    icon: 'pdf-txt',
    color: '#047857',
    bg: '#ECFDF5',
    category: 'from-pdf',
    endpoint: '/api/convert',
    params: { targetFormat: 'txt' },
    accept: '.pdf',
    actionLabel: 'Extract Text',
  },
];

export const CATEGORIES = [
  { id: 'all',       label: 'All Tools' },
  { id: 'organize',  label: 'Organize PDF' },
  { id: 'edit',      label: 'Edit PDF' },
  { id: 'to-pdf',    label: 'Convert to PDF' },
  { id: 'from-pdf',  label: 'Convert from PDF' },
];
